# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_standalone_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(627, 518)
        MainWindow.setMinimumSize(QtCore.QSize(627, 518))
        MainWindow.setMaximumSize(QtCore.QSize(627, 518))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 571, 151))
        self.label.setMouseTracking(False)
        self.label.setStyleSheet("background-color: #ffffff")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 190, 571, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.InputField = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.InputField.setContentsMargins(0, 0, 0, 0)
        self.InputField.setObjectName("InputField")
        self.link_entry = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.link_entry.setObjectName("link_entry")
        self.InputField.addWidget(self.link_entry)
        self.entry_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.entry_button.setObjectName("entry_button")
        self.InputField.addWidget(self.entry_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 280, 571, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.DeletingField = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.DeletingField.setContentsMargins(0, 0, 0, 0)
        self.DeletingField.setObjectName("DeletingField")
        self.link_entry_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.link_entry_2.setObjectName("link_entry_2")
        self.DeletingField.addWidget(self.link_entry_2)
        self.deleting_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.deleting_button.setObjectName("deleting_button")
        self.DeletingField.addWidget(self.deleting_button)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 380, 361, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 211, 41))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.timeEdit = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.timeEdit.setStyleSheet("font: 75 20pt \"Tlwg Typo\";")
        self.timeEdit.setObjectName("timeEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(200, 10, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.frame_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 370, 151, 121))
        self.pushButton_2.setStyleSheet("background-color: rgb(143, 240, 164);\n"
                                        "border-style: outset;\n"
                                        "border-radius: 60px;\n"
                                        "padding: 4px;")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.label.raise_()
        self.verticalLayoutWidget.raise_()
        self.pushButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Какой то текст, описывающий базовый функционал"))
        self.entry_button.setText(_translate("MainWindow", "Добавить"))
        self.deleting_button.setText(_translate("MainWindow", "Удалить"))
        self.label_2.setText(_translate("MainWindow", "Ввод времени, приглашение"))
        self.pushButton.setText(_translate("MainWindow", "Ввод"))
        self.pushButton_2.setText(_translate("MainWindow", "Старт"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
