# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'captha_handler.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CapthaHandler(object):
    def setupUi(self, CapthaHandler):
        CapthaHandler.setObjectName("CapthaHandler")
        CapthaHandler.resize(400, 266)
        self.image_field = QtWidgets.QLabel(CapthaHandler)
        self.image_field.setGeometry(QtCore.QRect(50, 20, 301, 171))
        self.image_field.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.image_field.setText("")
        self.image_field.setObjectName("image_field")
        self.captcha_input = QtWidgets.QLineEdit(CapthaHandler)
        self.captcha_input.setGeometry(QtCore.QRect(30, 220, 191, 25))
        self.captcha_input.setInputMask("")
        self.captcha_input.setText("")
        self.captcha_input.setObjectName("captcha_input")
        self.get_input_button = QtWidgets.QPushButton(CapthaHandler)
        self.get_input_button.setGeometry(QtCore.QRect(240, 220, 121, 31))
        self.get_input_button.setObjectName("get_input_button")

        self.retranslateUi(CapthaHandler)
        QtCore.QMetaObject.connectSlotsByName(CapthaHandler)

    def retranslateUi(self, CapthaHandler):
        _translate = QtCore.QCoreApplication.translate
        CapthaHandler.setWindowTitle(_translate("CapthaHandler", "Form"))
        self.captcha_input.setPlaceholderText(_translate("CapthaHandler", "Введите код с картинки"))
        self.get_input_button.setText(_translate("CapthaHandler", "Отправить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CapthaHandler = QtWidgets.QWidget()
    ui = Ui_CapthaHandler()
    ui.setupUi(CapthaHandler)
    CapthaHandler.show()
    sys.exit(app.exec_())
