# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vk_login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(393, 215)
        self.login_entry_field = QtWidgets.QLineEdit(RegistrationWindow)
        self.login_entry_field.setGeometry(QtCore.QRect(110, 50, 231, 25))
        self.login_entry_field.setText("")
        self.login_entry_field.setObjectName("login_entry_field")
        self.password_entry_field = QtWidgets.QLineEdit(RegistrationWindow)
        self.password_entry_field.setGeometry(QtCore.QRect(110, 90, 231, 25))
        self.password_entry_field.setObjectName("password_entry_field")
        self.pushButton = QtWidgets.QPushButton(RegistrationWindow)
        self.pushButton.setGeometry(QtCore.QRect(90, 150, 221, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../static/vk_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.is_password_viewable_button = QtWidgets.QPushButton(RegistrationWindow)
        self.is_password_viewable_button.setGeometry(QtCore.QRect(350, 90, 21, 21))
        self.is_password_viewable_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../static/crossed_eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.is_password_viewable_button.setIcon(icon1)
        self.is_password_viewable_button.setObjectName("is_password_viewable_button")
        self.LoginLabel = QtWidgets.QFrame(RegistrationWindow)
        self.LoginLabel.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.LoginLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LoginLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LoginLabel.setObjectName("LoginLabel")
        self.login_text = QtWidgets.QLabel(self.LoginLabel)
        self.login_text.setGeometry(QtCore.QRect(0, 0, 51, 21))
        self.login_text.setObjectName("login_text")
        self.mail_icon = QtWidgets.QLabel(self.LoginLabel)
        self.mail_icon.setGeometry(QtCore.QRect(60, 0, 21, 21))
        self.mail_icon.setText("")
        self.mail_icon.setPixmap(QtGui.QPixmap("../static/mail.png"))
        self.mail_icon.setScaledContents(True)
        self.mail_icon.setObjectName("mail_icon")
        self.PasswordLabel = QtWidgets.QFrame(RegistrationWindow)
        self.PasswordLabel.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.PasswordLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PasswordLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.password_text = QtWidgets.QLabel(self.PasswordLabel)
        self.password_text.setGeometry(QtCore.QRect(0, 0, 61, 17))
        self.password_text.setObjectName("password_text")
        self.password_icon = QtWidgets.QLabel(self.PasswordLabel)
        self.password_icon.setGeometry(QtCore.QRect(60, 0, 21, 20))
        self.password_icon.setText("")
        self.password_icon.setPixmap(QtGui.QPixmap("../static/password.png"))
        self.password_icon.setScaledContents(True)
        self.password_icon.setObjectName("password_icon")

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "Form"))
        self.pushButton.setText(_translate("RegistrationWindow", "Войти"))
        self.login_text.setText(_translate("RegistrationWindow", "Логин"))
        self.password_text.setText(_translate("RegistrationWindow", "Пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrationWindow = QtWidgets.QWidget()
    ui = Ui_RegistrationWindow()
    ui.setupUi(RegistrationWindow)
    RegistrationWindow.show()
    sys.exit(app.exec_())
